### PR TITLE
Replaced a few deprecated items.

### PR DESCRIPTION
**Pull request by gkjpettet**
- Replaced deprecated `FolderItem.TotalSeconds` with `FolderItemSecondsFrom1970`.
- Replaced deprecated `InvalidJSONException` with `JSONException`.
- Replaced the deprecate `JSONItem.Names()` with `JSONItems.Keys()`.

### CODE REVIEW

**Comment by sworteu** [comment]
Hi @gkjpettet could you be so kind to leave the Xtends methods as-is. You can keep the extention method unused but please don't remove the Xtends methods. Overall i see this pull request as OK when the extend method is kept intact.

**Comment by gkjpettet** [comment]
Can I ask why you want to keep a single extension method in a module? By combining it with the Express method you achieve the same effect but the end user only needs to import one module.

**Comment by sworteu** [comment]
> Can I ask why you want to keep a single extension method in a module? By combining it with the Express method you achieve the same effect but the end user only needs to import one module.

So you want to have everything in a single module i see that you added the method there. I'll rest my case. 
Is there any more changes to be added ?

**Comment by gkjpettet** [comment]
I have made many other changes that I will submit as an additional pull request as you might not like them (in which case I'll just keep them in my own fork). 

The other changes I've made on my local branch are that I've added property and method descriptions to almost everything in the module (so they show up in the syntax help in the IDE). Controversially however I've changed local variable names to begin with a lowercase letter rather than an uppercase letter since this is the typical Xojo style and I find it much easier to figure out the code when I can visually tell the difference between a local variable and a class property.

**Pull request merged**
